# Generated by Django 4.1.5 on 2023-01-21 17:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
